use std::fmt::Write as _;

use thiserror::Error;

use crate::{ExportFunction, ExportProjection, ProjectionValidationError};

const MAX_SCRIPT_BYTES: usize = 32 * 1024 * 1024;
const RECORDS_PER_METHOD: usize = 256;
// Java class files encode each string constant with a u16 byte length. Keep
// generated record-data constants comfortably below that hard limit while
// packing many records into each constant-pool entry.
const MAX_RECORD_DATA_LITERAL_BYTES: usize = 48 * 1024;
const MAX_CLASS_NAME_BYTES: usize = 128;

/// Failure to render a built-in Ghidra Java script.
#[derive(Debug, Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum GhidraJavaError {
    #[error("the export projection is invalid: {0}")]
    InvalidProjection(#[from] ProjectionValidationError),
    #[error("`{name}` is not a conservative Java class name")]
    InvalidClassName { name: String },
    #[error("the generated Ghidra Java script exceeds {limit} bytes")]
    OutputLimitExceeded { limit: usize },
}

#[derive(Debug)]
enum Record {
    Function(String),
    Global(String),
}

/// Render a deterministic Ghidra Java script with the supplied public class.
///
/// Ghidra requires the source filename to match this class name. The accepted
/// subset is deliberately conservative and excludes keywords, Unicode
/// confusables, path separators, and package syntax.
pub fn render_ghidra_java(
    projection: &ExportProjection,
    class_name: &str,
) -> Result<String, GhidraJavaError> {
    projection.validate()?;
    validate_ghidra_java_class_name(class_name)?;

    let records = collect_records(projection);
    let batch_count = records.len().div_ceil(RECORDS_PER_METHOD);
    let mut output = String::new();
    push_checked(
        &mut output,
        "// Generated by ReSymbol. Review before running.\n\
//@category ReSymbol\n\n\
import java.math.BigInteger;\n\
import java.nio.charset.StandardCharsets;\n\
import java.util.Base64;\n\n\
import ghidra.app.script.GhidraScript;\n\
import ghidra.program.model.address.Address;\n\
import ghidra.program.model.address.AddressSet;\n\
import ghidra.program.model.listing.Function;\n\
import ghidra.program.model.listing.FunctionManager;\n\
import ghidra.program.model.mem.Memory;\n\
import ghidra.program.model.symbol.SourceType;\n\
import ghidra.program.model.symbol.Symbol;\n\
import ghidra.program.model.symbol.SymbolTable;\n\n",
    )?;
    push_checked(
        &mut output,
        &format!("public class {class_name} extends GhidraScript {{\n"),
    )?;
    push_checked(
        &mut output,
        &format!(
            "    private static final String EXPECTED_SHA256 = {};\n",
            java_string_literal(projection.binary.id.as_str())
        ),
    )?;
    push_checked(
        &mut output,
        r#"
    private Address imageBase;
    private Memory memory;
    private FunctionManager functionManager;
    private SymbolTable symbolTable;

    @Override
    protected void run() throws Exception {
        // This check intentionally precedes every program mutation.
        verifyIdentity();
        imageBase = currentProgram.getImageBase();
        memory = currentProgram.getMemory();
        functionManager = currentProgram.getFunctionManager();
        symbolTable = currentProgram.getSymbolTable();
"#,
    )?;
    for batch in 0..batch_count {
        push_checked(&mut output, &format!("        applyBatch{batch}();\n"))?;
    }
    push_checked(
        &mut output,
        r#"        println("[ReSymbol] import complete");
    }

    private void verifyIdentity() {
        String actual = currentProgram.getExecutableSHA256();
        if (actual == null || !EXPECTED_SHA256.equalsIgnoreCase(actual)) {
            throw new IllegalStateException(
                "loaded program SHA-256 does not match this ReSymbol export"
            );
        }
    }

    private Address toAddress(BigInteger rva) throws Exception {
        if (rva.signum() < 0) {
            throw new IllegalArgumentException("negative RVA");
        }
        Address address = imageBase.addNoWrap(rva);
        if (!memory.contains(address)) {
            throw new IllegalArgumentException("resolved address is not mapped");
        }
        return address;
    }

    private boolean hasProtectedName(Address address) {
        for (Symbol symbol : symbolTable.getSymbols(address)) {
            SourceType source = symbol.getSource();
            if (source != SourceType.DEFAULT && source != SourceType.ANALYSIS) {
                return true;
            }
        }
        return false;
    }

    private boolean createKnownFunction(Address start, BigInteger size)
            throws Exception {
        if (size == null || size.signum() <= 0) {
            return false;
        }
        Address end = start.addNoWrap(size.subtract(BigInteger.ONE));
        if (!memory.contains(start, end)) {
            throw new IllegalArgumentException("function range is not wholly mapped");
        }
        if (functionManager.getFunctionAt(start) != null) {
            return true; // Never replace an existing function body.
        }
        if (functionManager.getFunctionContaining(start) != null) {
            throw new IllegalArgumentException(
                "function start lies inside an existing function"
            );
        }
        if (hasProtectedName(start)) {
            throw new IllegalStateException(
                "function start has a protected existing name"
            );
        }
        AddressSet body = new AddressSet(start, end); // End is inclusive in Ghidra.
        Function created = functionManager.createFunction(
            null, start, body, SourceType.ANALYSIS
        );
        if (created == null) {
            throw new IllegalStateException("Ghidra rejected an overlapping function body");
        }
        return true;
    }

    private void applyName(Address address, String name) throws Exception {
        if (name == null || hasProtectedName(address)) {
            return;
        }
        Function function = functionManager.getFunctionAt(address);
        if (function != null) {
            function.setName(name, SourceType.ANALYSIS);
        }
        else {
            createLabel(address, name, true, SourceType.ANALYSIS);
        }
    }

    private static String decodeName(String encoded) {
        return new String(
            Base64.getDecoder().decode(encoded), StandardCharsets.UTF_8
        );
    }

    private void report(String kind, String rva, Exception error) {
        printerr(
            "[ReSymbol] " + kind + " failed at RVA 0x" + rva + ": "
                + error.getClass().getSimpleName()
        );
    }

    private void applyRecordBatch(String records) {
        int start = 0;
        while (start < records.length()) {
            int end = records.indexOf('\n', start);
            if (end < 0) {
                end = records.length();
            }
            String record = records.substring(start, end);
            if (record.length() < 3 || record.charAt(1) != ',') {
                printerr("[ReSymbol] invalid generated record envelope");
            }
            else if (record.charAt(0) == 'F') {
                applyFunctionRecord(record.substring(2));
            }
            else if (record.charAt(0) == 'G') {
                applyGlobalRecord(record.substring(2));
            }
            else {
                printerr("[ReSymbol] invalid generated record kind");
            }
            start = end + 1;
        }
    }

    private void applyFunctionRecord(String record) {
        String[] fields = record.split(",", -1);
        if (fields.length != 3) {
            printerr("[ReSymbol] invalid generated function record");
            return;
        }

        BigInteger rva;
        BigInteger size;
        String name;
        Address start;
        try {
            rva = new BigInteger(fields[0], 16);
            size = fields[1].isEmpty() ? null : new BigInteger(fields[1], 16);
            name = fields[2].isEmpty() ? null : decodeName(fields[2]);
            start = toAddress(rva);
        }
        catch (Exception error) {
            report("function address", fields[0], error);
            return;
        }

        boolean functionReady = false;
        if (size != null) {
            try {
                functionReady = createKnownFunction(start, size);
            }
            catch (Exception error) {
                report("function range", fields[0], error);
            }
        }
        else {
            try {
                Function exact = functionManager.getFunctionAt(start);
                if (exact == null) {
                    if (functionManager.getFunctionContaining(start) != null) {
                        throw new IllegalArgumentException(
                            "function start lies inside an existing function"
                        );
                    }
                    throw new IllegalArgumentException(
                        "name-only claim has no function at the exact start"
                    );
                }
                functionReady = true;
            }
            catch (Exception error) {
                report("function identity", fields[0], error);
            }
        }
        if (functionReady) {
            try {
                applyName(start, name);
            }
            catch (Exception error) {
                report("function name", fields[0], error);
            }
        }
    }

    private void applyGlobalRecord(String record) {
        String[] fields = record.split(",", -1);
        if (fields.length != 2) {
            printerr("[ReSymbol] invalid generated global record");
            return;
        }
        try {
            BigInteger rva = new BigInteger(fields[0], 16);
            Address address = toAddress(rva);
            if (functionManager.getFunctionContaining(address) != null) {
                throw new IllegalArgumentException(
                    "global address lies in an existing function"
                );
            }
            applyName(address, decodeName(fields[1]));
        }
        catch (Exception error) {
            report("global name", fields[0], error);
        }
    }

"#,
    )?;

    for (batch, records) in records.chunks(RECORDS_PER_METHOD).enumerate() {
        let data = record_batch_data(records);
        push_checked(
            &mut output,
            &format!("    private void applyBatch{batch}() {{\n"),
        )?;
        push_checked(
            &mut output,
            &format!(
                "        StringBuilder records = new StringBuilder({});\n",
                data.len()
            ),
        )?;
        // The record envelope is ASCII-only, so byte slicing cannot split a
        // UTF-8 code point. StringBuilder prevents javac from folding adjacent
        // literals back into one oversized class-file string constant.
        for chunk_start in (0..data.len()).step_by(MAX_RECORD_DATA_LITERAL_BYTES) {
            let chunk_end = data
                .len()
                .min(chunk_start.saturating_add(MAX_RECORD_DATA_LITERAL_BYTES));
            push_checked(
                &mut output,
                &format!(
                    "        records.append({});\n",
                    java_string_literal(&data[chunk_start..chunk_end])
                ),
            )?;
        }
        push_checked(
            &mut output,
            "        applyRecordBatch(records.toString());\n",
        )?;
        push_checked(&mut output, "    }\n\n")?;
    }
    push_checked(&mut output, "}\n")?;

    Ok(output)
}

fn collect_records(projection: &ExportProjection) -> Vec<Record> {
    let accepted_sizes = non_overlapping_sizes(&projection.functions);
    let mut records = Vec::new();
    for (function, size) in projection.functions.iter().zip(&accepted_sizes) {
        if !emits_function_record(function, *size) {
            continue;
        }
        let size = size.map_or_else(String::new, |value| format!("{value:x}"));
        let name = function
            .selected_name
            .as_ref()
            .map_or_else(String::new, |value| {
                base64_encode(value.output_name.as_bytes())
            });
        records.push(Record::Function(format!(
            "{:x},{size},{name}",
            function.rva
        )));
    }
    for global in &projection.globals {
        let Some(name) = &global.selected_name else {
            continue;
        };
        if projection
            .functions
            .binary_search_by_key(&global.rva, |function| function.rva)
            .is_ok_and(|index| {
                emits_function_record(&projection.functions[index], accepted_sizes[index])
            })
        {
            continue;
        }
        records.push(Record::Global(format!(
            "{:x},{}",
            global.rva,
            base64_encode(name.output_name.as_bytes())
        )));
    }
    records
}

fn emits_function_record(function: &ExportFunction, accepted_size: Option<u64>) -> bool {
    function.selected_name.is_some() || accepted_size.is_some()
}

fn record_batch_data(records: &[Record]) -> String {
    let capacity = records
        .iter()
        .map(|record| match record {
            Record::Function(value) | Record::Global(value) => value.len().saturating_add(3),
        })
        .fold(0_usize, usize::saturating_add);
    let mut data = String::with_capacity(capacity);
    for record in records {
        let (kind, value) = match record {
            Record::Function(value) => ('F', value),
            Record::Global(value) => ('G', value),
        };
        data.push(kind);
        data.push(',');
        data.push_str(value);
        data.push('\n');
    }
    debug_assert!(data.is_ascii());
    data
}

fn non_overlapping_sizes(functions: &[ExportFunction]) -> Vec<Option<u64>> {
    let mut accepted = functions.iter().map(|value| value.size).collect::<Vec<_>>();
    let mut ranges = functions
        .iter()
        .enumerate()
        .filter_map(|(index, value)| {
            let size = value.size?;
            Some((index, value.rva, value.rva.checked_add(size)?))
        })
        .collect::<Vec<_>>();
    ranges.sort_by_key(|value| (value.1, value.2, value.0));

    let mut cluster_start = 0;
    while cluster_start < ranges.len() {
        let mut cluster_end = ranges[cluster_start].2;
        let mut next = cluster_start + 1;
        while next < ranges.len() && ranges[next].1 < cluster_end {
            cluster_end = cluster_end.max(ranges[next].2);
            next += 1;
        }
        if next - cluster_start > 1 {
            for value in &ranges[cluster_start..next] {
                accepted[value.0] = None;
            }
        }
        cluster_start = next;
    }
    accepted
}

/// Validate the conservative Java identifier subset accepted for Ghidra scripts.
pub fn validate_ghidra_java_class_name(class_name: &str) -> Result<(), GhidraJavaError> {
    let valid_length = !class_name.is_empty() && class_name.len() <= MAX_CLASS_NAME_BYTES;
    let mut bytes = class_name.bytes();
    let valid_start = bytes
        .next()
        .is_some_and(|value| value.is_ascii_alphabetic() || matches!(value, b'_' | b'$'));
    let valid_rest =
        bytes.all(|value| value.is_ascii_alphanumeric() || matches!(value, b'_' | b'$'));
    if valid_length && valid_start && valid_rest && !is_java_keyword(class_name) {
        Ok(())
    } else {
        Err(GhidraJavaError::InvalidClassName {
            name: class_name.to_owned(),
        })
    }
}

fn is_java_keyword(value: &str) -> bool {
    matches!(
        value,
        "abstract"
            | "assert"
            | "boolean"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extends"
            | "final"
            | "finally"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "implements"
            | "import"
            | "instanceof"
            | "int"
            | "interface"
            | "long"
            | "native"
            | "new"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "short"
            | "static"
            | "strictfp"
            | "super"
            | "switch"
            | "synchronized"
            | "this"
            | "throw"
            | "throws"
            | "transient"
            | "try"
            | "void"
            | "volatile"
            | "while"
            | "true"
            | "false"
            | "null"
            | "var"
            | "yield"
            | "record"
            | "sealed"
            | "permits"
            | "non-sealed"
            | "_"
            | "module"
            | "open"
            | "requires"
            | "transitive"
            | "exports"
            | "opens"
            | "to"
            | "uses"
            | "provides"
            | "with"
            | "when"
    )
}

fn java_string_literal(value: &str) -> String {
    let mut output = String::with_capacity(value.len().saturating_add(2));
    output.push('"');
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{08}' => output.push_str("\\b"),
            '\u{0c}' => output.push_str("\\f"),
            ' '..='~' => output.push(character),
            value if u32::from(value) <= 0xff => {
                write!(output, "\\{:03o}", u32::from(value))
                    .expect("writing to a String cannot fail");
            }
            value => {
                let mut units = [0_u16; 2];
                for unit in value.encode_utf16(&mut units) {
                    write!(output, "\\u{unit:04x}").expect("writing to a String cannot fail");
                }
            }
        }
    }
    output.push('"');
    output
}

fn base64_encode(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut output = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let first = chunk[0];
        let second = chunk.get(1).copied().unwrap_or(0);
        let third = chunk.get(2).copied().unwrap_or(0);
        output.push(char::from(ALPHABET[usize::from(first >> 2)]));
        output.push(char::from(
            ALPHABET[usize::from(((first & 0x03) << 4) | (second >> 4))],
        ));
        if chunk.len() >= 2 {
            output.push(char::from(
                ALPHABET[usize::from(((second & 0x0f) << 2) | (third >> 6))],
            ));
        } else {
            output.push('=');
        }
        if chunk.len() == 3 {
            output.push(char::from(ALPHABET[usize::from(third & 0x3f)]));
        } else {
            output.push('=');
        }
    }
    output
}

fn push_checked(output: &mut String, value: &str) -> Result<(), GhidraJavaError> {
    if output
        .len()
        .checked_add(value.len())
        .is_none_or(|length| length > MAX_SCRIPT_BYTES)
    {
        return Err(GhidraJavaError::OutputLimitExceeded {
            limit: MAX_SCRIPT_BYTES,
        });
    }
    output.push_str(value);
    Ok(())
}

#[cfg(test)]
mod tests {
    use resymbol_core::BinaryId;

    use super::*;
    use crate::{
        AttributedText, ExportAttribution, ExportBinary, ExportBinaryFormat,
        ExportControlFlowTarget, ExportDirectCall, ExportGlobal, ExportName, ExportProducer,
        ExportProvenance, ExportThunk,
    };

    fn attribution() -> ExportAttribution {
        ExportAttribution {
            confidence: 1.0,
            provenance: ExportProvenance {
                producer: ExportProducer::Core {
                    component: "test".to_owned(),
                    version: "1.0.0".to_owned(),
                },
                method: "test".to_owned(),
                run_id: None,
            },
        }
    }

    fn name(value: &str) -> ExportName {
        let output_name = if value == "global_name" {
            "global_name"
        } else {
            "quoted_safe_name"
        };
        ExportName {
            source: AttributedText {
                text: value.to_owned(),
                attribution: attribution(),
            },
            output_name: output_name.to_owned(),
        }
    }

    fn projection() -> ExportProjection {
        ExportProjection {
            schema_version: 6,
            binary: ExportBinary {
                id: BinaryId::from_sha256("22".repeat(32)).expect("test digest"),
                file_size: 0x3000,
                format: ExportBinaryFormat::Pe,
                architecture: "x86_64".to_owned(),
                image_base: 0x1_4000_0000,
                image_size: 0x5000,
            },
            functions: vec![ExportFunction {
                rva: 0x1000,
                entry_attribution: None,
                size: Some(0x20),
                size_attribution: Some(attribution()),
                selected_name: Some(name("quoted_\"_slash_\\_snowman_☃")),
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: vec![AttributedText {
                    text: "demo::Widget".to_owned(),
                    attribution: attribution(),
                }],
            }],
            globals: vec![ExportGlobal {
                rva: 0x2000,
                size: None,
                size_attribution: None,
                selected_name: Some(name("global_name")),
                alternate_names: Vec::new(),
            }],
            types: Vec::new(),
            direct_calls: Vec::new(),
            thunks: Vec::new(),
            strings: Vec::new(),
            data_references: Vec::new(),
            warnings: Vec::new(),
        }
    }

    #[test]
    fn rejects_unsafe_or_reserved_class_names() {
        assert!(validate_ghidra_java_class_name("ReSymbolImport").is_ok());
        assert!(validate_ghidra_java_class_name("Re$Symbol").is_ok());
        for invalid in ["", "9Import", "path/Import", "two.words", "class", "record"] {
            assert!(matches!(
                validate_ghidra_java_class_name(invalid),
                Err(GhidraJavaError::InvalidClassName { .. })
            ));
        }
    }

    #[test]
    fn renders_identity_gate_and_conservative_ghidra_operations() {
        let script = render_ghidra_java(&projection(), "ReSymbolImport").expect("render");
        let gate = script.find("verifyIdentity();").expect("identity gate");
        let batch = script.find("applyBatch0();").expect("batch call");
        assert!(gate < batch);
        assert!(script.contains("currentProgram.getExecutableSHA256()"));
        assert!(script.contains("imageBase.addNoWrap(rva)"));
        assert!(script.contains("memory.contains(start, end)"));
        assert!(script.contains("new AddressSet(start, end)"));
        assert!(script.contains("SourceType.ANALYSIS"));
        assert!(script.contains("source != SourceType.DEFAULT"));
        assert!(script.contains("source != SourceType.ANALYSIS"));
        assert!(script.contains("getFunctionContaining(start)"));
        assert!(script.contains("global address lies in an existing function"));
        assert!(!script.contains("setPlateComment"));
        assert!(!script.contains("setPreComment"));
    }

    #[test]
    fn names_are_utf8_base64_data_not_java_source() {
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
        assert_eq!(java_string_literal("x\"\\\n☃"), "\"x\\\"\\\\\\n\\u2603\"");

        let script = render_ghidra_java(&projection(), "ReSymbolImport").expect("render");
        assert!(!script.contains("quoted_\"_slash_\\_snowman_"));
        assert!(script.contains("Base64.getDecoder().decode(encoded)"));
    }

    #[test]
    fn rendering_is_byte_deterministic() {
        let projection = projection();
        assert_eq!(
            render_ghidra_java(&projection, "ReSymbolImport").expect("first"),
            render_ghidra_java(&projection, "ReSymbolImport").expect("second")
        );
    }

    #[test]
    fn entry_only_functions_and_relationships_emit_no_mutation_records() {
        let mut projection = projection();
        projection.functions = vec![
            ExportFunction {
                rva: 0x3000,
                entry_attribution: Some(attribution()),
                size: None,
                size_attribution: None,
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
            ExportFunction {
                rva: 0x4000,
                entry_attribution: Some(attribution()),
                size: None,
                size_attribution: None,
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
        ];
        projection.globals.clear();
        projection.direct_calls = vec![ExportDirectCall {
            caller_rva: 0x3000,
            call_site_rva: 0x3004,
            target: ExportControlFlowTarget::Function { rva: 0x4000 },
            attribution: attribution(),
        }];
        projection.thunks = vec![ExportThunk {
            rva: 0x4000,
            target: ExportControlFlowTarget::ImportIat { iat_rva: 0x2000 },
            attribution: attribution(),
        }];

        let script = render_ghidra_java(&projection, "ReSymbolImport")
            .expect("render entry-only projection");
        assert!(!script.contains("applyBatch0();"));
        assert!(!script.contains("3000,"));
        assert!(!script.contains("4000,"));
    }

    #[test]
    fn function_wins_when_a_global_shares_its_rva() {
        let mut projection = projection();
        projection.globals[0].rva = projection.functions[0].rva;

        let script = render_ghidra_java(&projection, "ReSymbolImport").expect("render");
        assert!(!script.contains("1000,Z2xvYmFsX25hbWU="));
        assert!(script.contains("1000,20,cXVvdGVkX3NhZmVfbmFtZQ=="));
    }

    #[test]
    fn entry_only_function_does_not_suppress_same_rva_named_global() {
        let mut projection = projection();
        projection.functions[0] = ExportFunction {
            rva: 0x1000,
            entry_attribution: Some(attribution()),
            size: None,
            size_attribution: None,
            selected_name: None,
            alternate_names: Vec::new(),
            prototypes: Vec::new(),
            class_memberships: Vec::new(),
        };
        projection.globals[0].rva = 0x1000;

        let script = render_ghidra_java(&projection, "ReSymbolImport")
            .expect("render shared-RVA entry evidence");
        assert!(script.contains("1000,Z2xvYmFsX25hbWU="));
        assert!(!script.contains("1000,,cXVvdGVkX3NhZmVfbmFtZQ=="));
    }

    #[test]
    fn named_or_sized_function_record_suppresses_same_rva_global() {
        let mut named = projection();
        named.functions[0].size = None;
        named.functions[0].size_attribution = None;
        named.globals[0].rva = 0x1000;

        let named_script =
            render_ghidra_java(&named, "ReSymbolImport").expect("render named function collision");
        assert!(named_script.contains("1000,,cXVvdGVkX3NhZmVfbmFtZQ=="));
        assert!(!named_script.contains("1000,Z2xvYmFsX25hbWU="));

        let mut sized = projection();
        sized.functions[0].selected_name = None;
        sized.globals[0].rva = 0x1000;

        let sized_script =
            render_ghidra_java(&sized, "ReSymbolImport").expect("render sized function collision");
        assert!(sized_script.contains("1000,20,"));
        assert!(!sized_script.contains("1000,Z2xvYmFsX25hbWU="));
    }

    #[test]
    fn renders_vngame_scale_runtime_function_sets_in_bounded_literals() {
        const VN_GAME_RUNTIME_FUNCTIONS: usize = 67_532;
        let mut projection = projection();
        projection.globals.clear();
        projection.binary.file_size = (VN_GAME_RUNTIME_FUNCTIONS as u64) * 2 + 1;
        projection.binary.image_size = (VN_GAME_RUNTIME_FUNCTIONS as u64) * 2 + 1;
        projection.functions = (0..VN_GAME_RUNTIME_FUNCTIONS)
            .map(|index| ExportFunction {
                rva: u64::try_from(index).expect("test index fits u64") * 2,
                entry_attribution: None,
                size: Some(1),
                size_attribution: Some(attribution()),
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            })
            .collect();

        let records = collect_records(&projection);
        assert_eq!(records.len(), VN_GAME_RUNTIME_FUNCTIONS);
        assert!(record_batch_data(&records[..RECORDS_PER_METHOD]).is_ascii());

        let script =
            render_ghidra_java(&projection, "ReSymbolImport").expect("VNGame-scale Ghidra export");
        let expected_batches = VN_GAME_RUNTIME_FUNCTIONS.div_ceil(RECORDS_PER_METHOD);
        assert_eq!(
            script.matches("private void applyBatch").count(),
            expected_batches
        );
        assert!(script.contains(&format!("applyBatch{}();", expected_batches - 1)));
        assert!(script.contains("StringBuilder records = new StringBuilder("));
        assert!(script.contains("applyRecordBatch(records.toString());"));
        assert!(script.len() < MAX_SCRIPT_BYTES);

        let gate = script.find("verifyIdentity();").expect("identity gate");
        let first_batch = script.find("applyBatch0();").expect("first batch");
        assert!(gate < first_batch);
    }
}
