use std::fmt::Write as _;

use thiserror::Error;

use crate::{ExportFunction, ExportProjection, ProjectionValidationError};

/// Hard ceiling for a generated bridge script.
///
/// Projection fields are bounded independently, but a writer also needs an
/// aggregate bound so an adversarial package cannot force an unbounded source
/// allocation.
const MAX_SCRIPT_BYTES: usize = 64 * 1024 * 1024;

/// Failure to render a self-contained IDAPython import bridge.
#[derive(Debug, Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum IdaPythonError {
    #[error("the export projection is invalid: {0}")]
    InvalidProjection(#[from] ProjectionValidationError),
    #[error("the generated IDAPython script exceeds {limit} bytes")]
    OutputLimitExceeded { limit: usize },
}

/// Render a deterministic, self-contained IDAPython symbol importer.
///
/// The generated script verifies IDA's recorded input SHA-256 before making
/// any database changes. Addresses are always reconstructed from IDA's loaded
/// image base plus an RVA, so normal rebasing is supported without weakening
/// exact-build binding.
pub fn render_ida_python(projection: &ExportProjection) -> Result<String, IdaPythonError> {
    projection.validate()?;

    let accepted_sizes = non_overlapping_sizes(&projection.functions);
    let mut output = String::new();
    push_checked(
        &mut output,
        "# Generated by ReSymbol. Review before running.\n\
import ida_bytes\n\
import ida_funcs\n\
import ida_idaapi\n\
import ida_name\n\
import ida_nalt\n\
import ida_segment\n\
import ida_ua\n\n",
    )?;
    push_checked(
        &mut output,
        &format!(
            "EXPECTED_SHA256 = {}\n\n",
            python_string_literal(projection.binary.id.as_str())
        ),
    )?;

    push_checked(&mut output, "FUNCTIONS = (\n")?;
    for (function, accepted_size) in projection.functions.iter().zip(&accepted_sizes) {
        if function.selected_name.is_none() && accepted_size.is_none() {
            continue;
        }
        let size = accepted_size.map_or_else(|| "None".to_owned(), |value| format!("0x{value:x}"));
        let name = function.selected_name.as_ref().map_or_else(
            || "None".to_owned(),
            |value| python_string_literal(&value.output_name),
        );
        push_checked(
            &mut output,
            &format!("    (0x{:x}, {size}, {name}),\n", function.rva),
        )?;
    }
    push_checked(&mut output, ")\n\nGLOBALS = (\n")?;
    for global in &projection.globals {
        let Some(name) = &global.selected_name else {
            continue;
        };
        if projection
            .functions
            .binary_search_by_key(&global.rva, |function| function.rva)
            .is_ok_and(|index| {
                projection.functions[index].selected_name.is_some()
                    || accepted_sizes[index].is_some()
            })
        {
            continue;
        }
        push_checked(
            &mut output,
            &format!(
                "    (0x{:x}, {}),\n",
                global.rva,
                python_string_literal(&name.output_name)
            ),
        )?;
    }
    push_checked(&mut output, ")\n\n")?;

    push_checked(
        &mut output,
        r#"def _verify_identity():
    actual = ida_nalt.retrieve_input_file_sha256()
    if not isinstance(actual, (bytes, bytearray)):
        raise RuntimeError("IDA has no SHA-256 for the loaded input; refusing to mutate the database")
    actual_hex = bytes(actual).hex().lower()
    if actual_hex != EXPECTED_SHA256:
        raise RuntimeError("loaded input SHA-256 does not match this ReSymbol export")


def _to_ea(image_base, rva):
    if rva < 0 or image_base < 0 or rva >= ida_idaapi.BADADDR:
        raise ValueError("RVA is outside IDA's address space")
    if image_base > ida_idaapi.BADADDR - rva:
        raise ValueError("loaded image base plus RVA overflows IDA's address space")
    ea = image_base + rva
    if ea == ida_idaapi.BADADDR or not ida_bytes.is_mapped(ea):
        raise ValueError("resolved address is not mapped")
    return ea


def _range_is_mapped(start, size):
    if size is None or size <= 0 or start > ida_idaapi.BADADDR - (size - 1):
        return False
    last = start + size - 1
    segment = ida_segment.getseg(start)
    return (
        segment is not None
        and last < segment.end_ea
        and ida_bytes.is_mapped(last)
    )


def _create_known_function(start, size):
    if not _range_is_mapped(start, size):
        raise ValueError("function range is not wholly mapped in one segment")

    existing = ida_funcs.get_func(start)
    if existing is not None:
        if existing.start_ea != start:
            raise ValueError("function start lies inside an existing function")
        return True

    end = start + size
    following = ida_funcs.get_next_func(start)
    if following is not None and following.start_ea < end:
        raise ValueError("function range overlaps an existing function")

    flags = ida_bytes.get_full_flags(start)
    if not ida_bytes.is_code(flags):
        if not ida_bytes.is_unknown(flags):
            raise ValueError("function start is occupied by non-code data")
        if ida_ua.create_insn(start) == 0:
            raise RuntimeError("IDA could not create an instruction at the function start")

    if not ida_funcs.add_func(start, end):
        raise RuntimeError("IDA rejected the function range")
    return True


def _has_exact_function(start):
    existing = ida_funcs.get_func(start)
    if existing is None:
        return False
    if existing.start_ea != start:
        raise ValueError("function start lies inside an existing function")
    return True


def _apply_name(ea, name):
    if name is None:
        return
    flags = ida_bytes.get_full_flags(ea)
    if ida_bytes.has_user_name(flags):
        print("[ReSymbol] kept user name at 0x{:x}".format(ea))
        return
    name_flags = ida_name.SN_CHECK | ida_name.SN_NOWARN | ida_name.SN_NON_AUTO
    if not ida_name.set_name(ea, name, name_flags):
        raise RuntimeError("IDA rejected the projected name")


def _report(kind, rva, error):
    print("[ReSymbol] {} failed at RVA 0x{:x}: {}".format(kind, rva, type(error).__name__))


def _apply_function(image_base, rva, size, name):
    try:
        start = _to_ea(image_base, rva)
    except Exception as error:
        _report("function address", rva, error)
        return

    function_ready = False
    if size is not None:
        try:
            function_ready = _create_known_function(start, size)
        except Exception as error:
            _report("function range", rva, error)
    else:
        try:
            function_ready = _has_exact_function(start)
            if not function_ready:
                raise ValueError("name-only claim has no function at the exact start")
        except Exception as error:
            _report("function identity", rva, error)

    if function_ready:
        try:
            _apply_name(start, name)
        except Exception as error:
            _report("function name", rva, error)


def _apply_global(image_base, rva, name):
    try:
        ea = _to_ea(image_base, rva)
        if ida_funcs.get_func(ea) is not None:
            raise ValueError("global address lies in an existing function")
        _apply_name(ea, name)
    except Exception as error:
        _report("global name", rva, error)


def main():
    # This check intentionally precedes image traversal and every mutation.
    _verify_identity()
    image_base = ida_nalt.get_imagebase()
    for rva, size, name in FUNCTIONS:
        _apply_function(image_base, rva, size, name)
    for rva, name in GLOBALS:
        _apply_global(image_base, rva, name)
    print("[ReSymbol] import complete")


if __name__ == "__main__":
    main()
"#,
    )?;

    Ok(output)
}

fn non_overlapping_sizes(functions: &[ExportFunction]) -> Vec<Option<u64>> {
    let mut accepted = functions.iter().map(|value| value.size).collect::<Vec<_>>();
    let mut ranges = functions
        .iter()
        .enumerate()
        .filter_map(|(index, value)| {
            let size = value.size?;
            let end = value.rva.checked_add(size)?;
            Some((index, value.rva, end))
        })
        .collect::<Vec<_>>();
    ranges.sort_by_key(|value| (value.1, value.2, value.0));

    let mut cluster_start = 0;
    while cluster_start < ranges.len() {
        let mut cluster_end = ranges[cluster_start].2;
        let mut next = cluster_start + 1;
        while next < ranges.len() && ranges[next].1 < cluster_end {
            cluster_end = cluster_end.max(ranges[next].2);
            next += 1;
        }
        if next - cluster_start > 1 {
            for value in &ranges[cluster_start..next] {
                accepted[value.0] = None;
            }
        }
        cluster_start = next;
    }
    accepted
}

fn python_string_literal(value: &str) -> String {
    let mut output = String::with_capacity(value.len().saturating_add(2));
    output.push('"');
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{08}' => output.push_str("\\b"),
            '\u{0c}' => output.push_str("\\f"),
            ' '..='~' => output.push(character),
            value if u32::from(value) <= 0xffff => {
                write!(output, "\\u{:04x}", u32::from(value))
                    .expect("writing to a String cannot fail");
            }
            value => {
                write!(output, "\\U{:08x}", u32::from(value))
                    .expect("writing to a String cannot fail");
            }
        }
    }
    output.push('"');
    output
}

fn push_checked(output: &mut String, value: &str) -> Result<(), IdaPythonError> {
    if output
        .len()
        .checked_add(value.len())
        .is_none_or(|length| length > MAX_SCRIPT_BYTES)
    {
        return Err(IdaPythonError::OutputLimitExceeded {
            limit: MAX_SCRIPT_BYTES,
        });
    }
    output.push_str(value);
    Ok(())
}

#[cfg(test)]
mod tests {
    use resymbol_core::BinaryId;

    use super::*;
    use crate::{
        AttributedText, ExportAttribution, ExportBinary, ExportBinaryFormat,
        ExportControlFlowTarget, ExportDirectCall, ExportGlobal, ExportName, ExportProducer,
        ExportProvenance, ExportThunk,
    };

    fn attribution() -> ExportAttribution {
        ExportAttribution {
            confidence: 1.0,
            provenance: ExportProvenance {
                producer: ExportProducer::Core {
                    component: "test".to_owned(),
                    version: "1.0.0".to_owned(),
                },
                method: "test".to_owned(),
                run_id: None,
            },
        }
    }

    fn name(value: &str) -> ExportName {
        let output_name = if value == "global_name" {
            "global_name"
        } else {
            "quoted_safe_name"
        };
        ExportName {
            source: AttributedText {
                text: value.to_owned(),
                attribution: attribution(),
            },
            output_name: output_name.to_owned(),
        }
    }

    fn projection() -> ExportProjection {
        ExportProjection {
            schema_version: 3,
            binary: ExportBinary {
                id: BinaryId::from_sha256("11".repeat(32)).expect("test digest"),
                file_size: 0x3000,
                format: ExportBinaryFormat::Pe,
                architecture: "x86_64".to_owned(),
                image_base: 0x1_4000_0000,
                image_size: 0x5000,
            },
            functions: vec![ExportFunction {
                rva: 0x1000,
                entry_attribution: None,
                size: Some(0x20),
                size_attribution: Some(attribution()),
                selected_name: Some(name("quoted_\"_slash_\\_snowman_☃")),
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: vec![AttributedText {
                    text: "demo::Widget".to_owned(),
                    attribution: attribution(),
                }],
            }],
            globals: vec![ExportGlobal {
                rva: 0x2000,
                size: None,
                size_attribution: None,
                selected_name: Some(name("global_name")),
                alternate_names: Vec::new(),
            }],
            types: Vec::new(),
            direct_calls: Vec::new(),
            thunks: Vec::new(),
            warnings: Vec::new(),
        }
    }

    #[test]
    fn renders_identity_gate_before_all_mutation() {
        let script = render_ida_python(&projection()).expect("render");
        let gate = script
            .find("_verify_identity()\n    image_base")
            .expect("gate");
        let loop_position = script
            .find("for rva, size, name in FUNCTIONS")
            .expect("loop");
        assert!(gate < loop_position);
        assert!(script.contains("retrieve_input_file_sha256"));
        assert!(script.contains("image_base + rva"));
        assert!(script.contains("ida_bytes.is_mapped"));
        assert!(script.contains("ida_bytes.has_user_name"));
        assert!(script.contains("ida_ua.create_insn"));
        assert!(script.contains("ida_funcs.add_func(start, end)"));
        assert!(script.contains("function_ready = _create_known_function"));
        assert!(script.contains("function_ready = _has_exact_function"));
        assert!(script.contains("global address lies in an existing function"));
        assert!(!script.contains("set_cmt"));
    }

    #[test]
    fn source_literals_cannot_break_out_of_python_strings() {
        assert_eq!(python_string_literal("x\"\\\n☃"), "\"x\\\"\\\\\\n\\u2603\"");
        let script = render_ida_python(&projection()).expect("render");
        assert!(script.contains("quoted_safe_name"));
        assert!(!script.contains("quoted_\"_slash_\\_snowman_"));
        assert!(!script.contains("snowman_☃"));
    }

    #[test]
    fn overlapping_ranges_are_never_offered_for_creation() {
        let functions = vec![
            ExportFunction {
                rva: 0x100,
                entry_attribution: None,
                size: Some(0x100),
                size_attribution: Some(attribution()),
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
            ExportFunction {
                rva: 0x180,
                entry_attribution: None,
                size: Some(0x10),
                size_attribution: Some(attribution()),
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
            ExportFunction {
                rva: 0x300,
                entry_attribution: None,
                size: Some(0x10),
                size_attribution: Some(attribution()),
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
        ];
        assert_eq!(
            non_overlapping_sizes(&functions),
            vec![None, None, Some(0x10)]
        );
    }

    #[test]
    fn rendering_is_byte_deterministic() {
        let projection = projection();
        assert_eq!(
            render_ida_python(&projection).expect("first"),
            render_ida_python(&projection).expect("second")
        );
    }

    #[test]
    fn entry_only_functions_and_relationships_emit_no_mutation_records() {
        let mut projection = projection();
        projection.functions = vec![
            ExportFunction {
                rva: 0x3000,
                entry_attribution: Some(attribution()),
                size: None,
                size_attribution: None,
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
            ExportFunction {
                rva: 0x4000,
                entry_attribution: Some(attribution()),
                size: None,
                size_attribution: None,
                selected_name: None,
                alternate_names: Vec::new(),
                prototypes: Vec::new(),
                class_memberships: Vec::new(),
            },
        ];
        projection.globals.clear();
        projection.direct_calls = vec![ExportDirectCall {
            caller_rva: 0x3000,
            call_site_rva: 0x3004,
            target: ExportControlFlowTarget::Function { rva: 0x4000 },
            attribution: attribution(),
        }];
        projection.thunks = vec![ExportThunk {
            rva: 0x4000,
            target: ExportControlFlowTarget::ImportIat { iat_rva: 0x2000 },
            attribution: attribution(),
        }];

        let script = render_ida_python(&projection).expect("render entry-only projection");
        assert!(script.contains("FUNCTIONS = (\n)\n\nGLOBALS = (\n)"));
        assert!(!script.contains("    (0x3000,"));
        assert!(!script.contains("    (0x4000,"));
    }

    #[test]
    fn function_wins_when_a_global_shares_its_rva() {
        let mut projection = projection();
        projection.globals[0].rva = projection.functions[0].rva;

        let script = render_ida_python(&projection).expect("render");
        assert!(!script.contains("(0x1000, \"global_name\")"));
        assert!(script.contains("(0x1000, 0x20, \"quoted_safe_name\")"));
    }
}
