<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>ReSymbol.ManagedHost.SlowFixture</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ReSymbol.PluginSdk/ReSymbol.PluginSdk.csproj" />
  </ItemGroup>
</Project>
