[package]
name = "resymbol-cli"
description = "Command-line interface for ReSymbol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "resymbol"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
resymbol-core = { path = "../resymbol-core" }

[dev-dependencies]
tempfile = "3.20.0"

[lints]
workspace = true
